Repository Nolmung/Nolmung-server, pull requests merged in 2024-11, with the labels that each got.

#1 env/SV-89: 백 초기 설정, 패키지 구조 설계
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/ureca/nolmung/business/dummy/DummyService.java
  src/main/java/ureca/nolmung/business/dummy/DummyUseCase.java
  src/main/java/ureca/nolmung/business/dummy/dto/request/AddDummyReq.java
  src/main/java/ureca/nolmung/business/dummy/dto/response/AddDummyResp.java
  src/main/java/ureca/nolmung/implementation/dummy/DummyManager.java
  src/main/java/ureca/nolmung/implementation/dummy/dtomapper/DummyDtoMapper.java
  src/main/java/ureca/nolmung/jpa/config/BaseEntity.java
  src/main/java/ureca/nolmung/jpa/config/JpaConfig.java
  src/main/java/ureca/nolmung/jpa/dummy/Dummy.java
  src/main/java/ureca/nolmung/persistence/dummy/DummyRepository.java
  src/main/java/ureca/nolmung/presentation/controller/dummy/DummyController.java
Labels: ⚙️ 환경 설정

#2 feat/SV-109: 공통 예외처리 포맷 개발
  src/main/java/ureca/nolmung/exception/BaseException.java
  src/main/java/ureca/nolmung/exception/ExceptionResponse.java
  src/main/java/ureca/nolmung/exception/ExceptionStatus.java
  src/main/java/ureca/nolmung/exception/ExceptionType.java
  src/main/java/ureca/nolmung/exception/Status.java
  src/main/java/ureca/nolmung/implementation/dummy/DummyException.java
  src/main/java/ureca/nolmung/implementation/dummy/DummyExceptionType.java
  src/main/java/ureca/nolmung/implementation/dummy/dummy.txt
Labels: 💻 기능

#8 feat/SV-194: Add all entities
  src/main/java/ureca/nolmung/jpa/badge/Badge.java
  src/main/java/ureca/nolmung/jpa/badgeCode/BadgeCode.java
  src/main/java/ureca/nolmung/jpa/bookmark/Bookmark.java
  src/main/java/ureca/nolmung/jpa/diary/Diary.java
  src/main/java/ureca/nolmung/jpa/diaryPlace/DiaryPlace.java
  src/main/java/ureca/nolmung/jpa/dog/Dog.java
  src/main/java/ureca/nolmung/jpa/dog/Enum/Gender.java
  src/main/java/ureca/nolmung/jpa/dogDiary/DogDiary.java
  src/main/java/ureca/nolmung/jpa/label/Label.java
  src/main/java/ureca/nolmung/jpa/media/Enum/MediaType.java
  src/main/java/ureca/nolmung/jpa/media/Media.java
  src/main/java/ureca/nolmung/jpa/place/Enum/Category.java
  src/main/java/ureca/nolmung/jpa/place/Place.java
  src/main/java/ureca/nolmung/jpa/recommend/Recommend.java
  src/main/java/ureca/nolmung/jpa/review/Review.java
  src/main/java/ureca/nolmung/jpa/reviewLabel/ReviewLabel.java
  src/main/java/ureca/nolmung/jpa/user/Enum/Gender.java
  src/main/java/ureca/nolmung/jpa/user/Enum/Provider.java
  src/main/java/ureca/nolmung/jpa/user/Enum/UserRole.java
  src/main/java/ureca/nolmung/jpa/user/Enum/UserStatus.java
  src/main/java/ureca/nolmung/jpa/user/User.java
Labels: 💻 기능

#10 fix/SV-194: Change data type in Recommend table
  src/main/java/ureca/nolmung/jpa/recommend/Recommend.java
Labels: 🐞 버그

#12 feat/SV-31: 후기 등록 및 삭제 API 개발
  src/main/java/ureca/nolmung/business/review/ReviewService.java
  src/main/java/ureca/nolmung/business/review/ReviewUseCase.java
  src/main/java/ureca/nolmung/business/review/dto/request/AddReviewReq.java
  src/main/java/ureca/nolmung/business/review/dto/response/AddReviewResp.java
  src/main/java/ureca/nolmung/exception/label/LabelException.java
  src/main/java/ureca/nolmung/exception/label/LabelExceptionType.java
  src/main/java/ureca/nolmung/exception/place/PlaceException.java
  src/main/java/ureca/nolmung/exception/place/PlaceExceptionType.java
  src/main/java/ureca/nolmung/exception/review/ReviewException.java
  src/main/java/ureca/nolmung/exception/review/ReviewExceptionType.java
  src/main/java/ureca/nolmung/implementation/review/ReviewManager.java
  src/main/java/ureca/nolmung/implementation/review/dtomapper/ReviewDtoMapper.java
  src/main/java/ureca/nolmung/jpa/dog/Dog.java
  src/main/java/ureca/nolmung/jpa/dog/Enum/DogSize.java
  src/main/java/ureca/nolmung/jpa/label/Label.java
  src/main/java/ureca/nolmung/jpa/label/LabelId.java
  src/main/java/ureca/nolmung/jpa/place/Enum/Category.java
  src/main/java/ureca/nolmung/jpa/place/Place.java
  src/main/java/ureca/nolmung/jpa/review/Review.java
  src/main/java/ureca/nolmung/jpa/reviewLabel/ReviewLabel.java
  src/main/java/ureca/nolmung/persistence/label/LabelRepository.java
  src/main/java/ureca/nolmung/persistence/place/PlaceRepository.java
  src/main/java/ureca/nolmung/persistence/review/ReviewRepository.java
  src/main/java/ureca/nolmung/persistence/user/UserRepository.java
  src/main/java/ureca/nolmung/presentation/controller/review/ReviewController.java
Labels: 💻 기능

#16 env/SV-79: Add Dockerfile
  Dockerfile
Labels: ⚙️ 환경 설정

#19 Update gradle.yml
  .github/workflows/gradle.yml
Labels: ⚙️ 환경 설정

#21 Update gradle.yml
  .github/workflows/gradle.yml
Labels: ⚙️ 환경 설정

#22 Update gradle.yml
  .github/workflows/gradle.yml
Labels: ⚙️ 환경 설정

#24 Update gradle.yml
  .github/workflows/gradle.yml
Labels: ⚙️ 환경 설정

#26 Update gradle.yml
  .github/workflows/gradle.yml
Labels: ⚙️ 환경 설정

#28 feat/SV-19: 소셜로그인, 회원가입 API 구현 및 JWT 토큰 인증 로직 개발
  build.gradle
  src/main/java/ureca/nolmung/business/oauth/OAuth2SucessHandler.java
  src/main/java/ureca/nolmung/business/oauth/OAuthUserServiceImplement.java
  src/main/java/ureca/nolmung/business/oauth/dto/CustomOauth2User.java
  src/main/java/ureca/nolmung/business/user/UserService.java
  src/main/java/ureca/nolmung/business/user/dto/request/SignUpReq.java
  src/main/java/ureca/nolmung/config/jwt/JWTUtil.java
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ureca/nolmung/config/security/SecurityConfig.java
  src/main/java/ureca/nolmung/exception/jwt/JwtException.java
  src/main/java/ureca/nolmung/exception/jwt/JwtExceptionType.java
  src/main/java/ureca/nolmung/exception/user/UserException.java
  src/main/java/ureca/nolmung/exception/user/UserExceptionType.java
  src/main/java/ureca/nolmung/jpa/user/Enum/UserRole.java
  src/main/java/ureca/nolmung/jpa/user/User.java
  src/main/java/ureca/nolmung/persistence/user/UserRepository.java
  src/main/java/ureca/nolmung/presentation/controller/oauth/MyController.java
  src/main/java/ureca/nolmung/presentation/controller/oauth/UserController.java
Labels: 💻 기능

#30 Update gradle.yml
  .github/workflows/gradle.yml
Labels: ⚙️ 환경 설정

#32 feat/SV-163: 오늘멍 등록 API 구현
  src/main/java/ureca/nolmung/business/diary/DiaryService.java
  src/main/java/ureca/nolmung/business/diary/DiaryUseCase.java
  src/main/java/ureca/nolmung/business/diary/dto/request/AddDiaryReq.java
  src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
  src/main/java/ureca/nolmung/implementation/dog/DogException.java
  src/main/java/ureca/nolmung/implementation/dog/DogExceptionType.java
  src/main/java/ureca/nolmung/implementation/media/MediaException.java
  src/main/java/ureca/nolmung/implementation/media/MediaExceptionType.java
  src/main/java/ureca/nolmung/jpa/diary/Diary.java
  src/main/java/ureca/nolmung/jpa/media/Media.java
  src/main/java/ureca/nolmung/persistence/dog/DogRepository.java
  src/main/java/ureca/nolmung/persistence/dogdiary/DogDiaryRepository.java
  src/main/java/ureca/nolmung/presentation/controller/diary/DiaryController.java
Labels: 💻 기능

#33 feat/SV-200: 시큐리티 설정에 swagger 관련 설정 추가
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ureca/nolmung/config/security/SecurityConfig.java
Labels: ⚙️ 환경 설정

#34 feat/SV-33: 반려견 프로필 등록 API 구현
  src/main/java/ureca/nolmung/business/dog/DogService.java
  src/main/java/ureca/nolmung/business/dog/DogUseCase.java
  src/main/java/ureca/nolmung/business/dog/dto/request/DogReq.java
  src/main/java/ureca/nolmung/business/dog/dto/response/DogResp.java
  src/main/java/ureca/nolmung/implementation/dog/DogManager.java
  src/main/java/ureca/nolmung/implementation/dog/dtomapper/DogDtoMapper.java
  src/main/java/ureca/nolmung/implementation/user/UserManager.java
  src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
Labels: 💻 기능

#36 feat/SV-117: 수도권 전체 개인 맞춤형 추천 로직 구현
  build.gradle
  src/main/java/ureca/nolmung/business/recommend/RecommendService.java
  src/main/java/ureca/nolmung/business/recommend/RecommendUseCase.java
  src/main/java/ureca/nolmung/business/recommend/dto/response/RecommendResp.java
  src/main/java/ureca/nolmung/implementation/recommend/AwsConfig.java
  src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
  src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
  src/main/java/ureca/nolmung/implementation/recommend/dtomapper/RecommendDtoMapper.java
  src/main/java/ureca/nolmung/presentation/controller/recommend/RecommendController.java
Labels: 💻 기능

#37 feat/SV-46: 반려견 프로필 수정 API 구현
  src/main/java/ureca/nolmung/business/dog/DogService.java
  src/main/java/ureca/nolmung/business/dog/DogUseCase.java
  src/main/java/ureca/nolmung/implementation/dog/DogManager.java
  src/main/java/ureca/nolmung/jpa/dog/Dog.java
  src/main/java/ureca/nolmung/persistence/dog/DogRepository.java
  src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
Labels: 💻 기능

#38 feat/SV-36: 장소 상세 정보 조회 API 개발
  build.gradle
  src/main/java/ureca/nolmung/business/place/PlaceService.java
  src/main/java/ureca/nolmung/business/place/PlaceUseCase.java
  src/main/java/ureca/nolmung/business/place/response/PlaceDetailResponse.java
  src/main/java/ureca/nolmung/config/security/SecurityConfig.java
  src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
  src/main/java/ureca/nolmung/implementation/place/PlaceExceptionType.java
  src/main/java/ureca/nolmung/implementation/place/PlaceManager.java
  src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
  src/main/java/ureca/nolmung/jpa/place/Place.java
  src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryCustom.java
  src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryImpl.java
  src/main/java/ureca/nolmung/presentation/controller/place/PlaceController.java
Labels: 💻 기능

#39 feat/SV-47: 반려견 프로필 삭제 API 구현
  src/main/java/ureca/nolmung/business/dog/DogService.java
  src/main/java/ureca/nolmung/business/dog/DogUseCase.java
  src/main/java/ureca/nolmung/implementation/dog/DogManager.java
  src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
Labels: 💻 기능

#40 feat/SV-172: 반려견 프로필 조회 API 구현
  src/main/java/ureca/nolmung/business/dog/DogService.java
  src/main/java/ureca/nolmung/business/dog/DogUseCase.java
  src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
Labels: 💻 기능

#41 feat/SV-108: 반려견 프로필 목록 조회 API 구현
  src/main/java/ureca/nolmung/business/dog/DogService.java
  src/main/java/ureca/nolmung/business/dog/DogUseCase.java
  src/main/java/ureca/nolmung/implementation/dog/DogManager.java
  src/main/java/ureca/nolmung/persistence/dog/DogRepository.java
  src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
Labels: 💻 기능

#42 feat/SV-111: 수도권 전체 즐겨찾기 수, 반려견 정보 기준 장소 추천 로직 구현
  src/main/java/ureca/nolmung/business/recommend/RecommendService.java
  src/main/java/ureca/nolmung/business/recommend/RecommendUseCase.java
  src/main/java/ureca/nolmung/business/recommend/dto/response/RecommendResp.java
  src/main/java/ureca/nolmung/implementation/dog/DogManager.java
  src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
  src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
  src/main/java/ureca/nolmung/implementation/recommend/dtomapper/RecommendDtoMapper.java
  src/main/java/ureca/nolmung/jpa/place/Place.java
  src/main/java/ureca/nolmung/persistence/place/PlaceRepository.java
  src/main/java/ureca/nolmung/presentation/controller/recommend/RecommendController.java
Labels: 💻 기능

#43 feat/sv-21: 거주지 근처 장소 추천 로직 구현
  src/main/java/ureca/nolmung/business/recommend/RecommendService.java
  src/main/java/ureca/nolmung/business/recommend/RecommendUseCase.java
  src/main/java/ureca/nolmung/config/security/SecurityConfig.java
  src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
  src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
  src/main/java/ureca/nolmung/implementation/recommend/dtomapper/RecommendDtoMapper.java
  src/main/java/ureca/nolmung/jpa/user/User.java
  src/main/java/ureca/nolmung/persistence/place/PlaceRepository.java
  src/main/java/ureca/nolmung/presentation/controller/recommend/RecommendController.java
Labels: 💻 기능

#48 feat/SV-197: 장소 검색 필터링 기능 개발
  src/main/java/ureca/nolmung/business/place/PlaceService.java
  src/main/java/ureca/nolmung/business/place/PlaceUseCase.java
  src/main/java/ureca/nolmung/implementation/place/PlaceManager.java
  src/main/java/ureca/nolmung/jpa/place/Enum/Category.java
  src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryCustom.java
  src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryImpl.java
  src/main/java/ureca/nolmung/presentation/controller/place/PlaceController.java
Labels: 💻 기능

#50 feat/SV-157: 오늘멍 상세조회 API 구현
  src/main/java/ureca/nolmung/business/diary/DiaryService.java
  src/main/java/ureca/nolmung/business/diary/DiaryUseCase.java
  src/main/java/ureca/nolmung/business/diary/dto/response/DiaryDetailResp.java
  src/main/java/ureca/nolmung/implementation/diary/DiaryExceptionType.java
  src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
  src/main/java/ureca/nolmung/implementation/diary/dtomapper/DiaryDtoMapper.java
  src/main/java/ureca/nolmung/implementation/diaryplace/DiaryPlaceManager.java
  src/main/java/ureca/nolmung/implementation/dog/DogManager.java
  src/main/java/ureca/nolmung/implementation/dogdiary/DogDiaryManager.java
  src/main/java/ureca/nolmung/implementation/media/MediaManager.java
  src/main/java/ureca/nolmung/persistence/diary/DiaryRepository.java
  src/main/java/ureca/nolmung/persistence/diaryplace/DiaryPlaceRepository.java
  src/main/java/ureca/nolmung/persistence/dogdiary/DogDiaryRepository.java
  src/main/java/ureca/nolmung/persistence/media/MediaRepository.java
  src/main/java/ureca/nolmung/presentation/controller/diary/DiaryController.java
Labels: 💻 기능

#51 refact/SV-204: 예외처리 파일 위치 변경
  src/main/java/ureca/nolmung/business/bookmark/BookmarkService.java
  src/main/java/ureca/nolmung/business/user/UserService.java
  src/main/java/ureca/nolmung/exception/ApiControllerAdvice.java
  src/main/java/ureca/nolmung/implementation/bookmark/BookmarkException.java
  src/main/java/ureca/nolmung/implementation/bookmark/BookmarkExceptionType.java
  src/main/java/ureca/nolmung/implementation/bookmark/BookmarkManager.java
  src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
  src/main/java/ureca/nolmung/implementation/diaryplace/DiaryPlaceManager.java
  src/main/java/ureca/nolmung/implementation/label/LabelException.java
  src/main/java/ureca/nolmung/implementation/label/LabelExceptionType.java
  src/main/java/ureca/nolmung/implementation/place/PlaceException.java
  src/main/java/ureca/nolmung/implementation/place/PlaceExceptionType.java
  src/main/java/ureca/nolmung/implementation/place/PlaceManager.java
  src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
  src/main/java/ureca/nolmung/implementation/review/ReviewException.java
  src/main/java/ureca/nolmung/implementation/review/ReviewExceptionType.java
  src/main/java/ureca/nolmung/implementation/review/ReviewManager.java
  src/main/java/ureca/nolmung/implementation/user/UserException.java
  src/main/java/ureca/nolmung/implementation/user/UserExceptionType.java
  src/main/java/ureca/nolmung/implementation/user/UserManager.java
Labels: 🛠️ 리팩토링

#53 refact/SV-205: 지도에서 장소 검색 Method 수정
  src/main/java/ureca/nolmung/business/place/PlaceService.java
  src/main/java/ureca/nolmung/business/place/PlaceUseCase.java
  src/main/java/ureca/nolmung/business/place/request/PlaceOnMapServiceRequest.java
  src/main/java/ureca/nolmung/implementation/place/PlaceManager.java
  src/main/java/ureca/nolmung/presentation/controller/place/PlaceController.java
  src/main/java/ureca/nolmung/presentation/controller/place/request/PlaceOnMapRequest.java
Labels: 🛠️ 리팩토링, 🔨 수정

#54 feat/SV-150: 오늘멍 삭제 API 구현
  src/main/java/ureca/nolmung/business/diary/DiaryService.java
  src/main/java/ureca/nolmung/business/diary/DiaryUseCase.java
  src/main/java/ureca/nolmung/business/diary/dto/response/DeleteDiaryResp.java
  src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
  src/main/java/ureca/nolmung/jpa/diary/Diary.java
  src/main/java/ureca/nolmung/persistence/diary/DiaryRepository.java
  src/main/java/ureca/nolmung/presentation/controller/diary/DiaryController.java
Labels: 💻 기능
