Repository Nolmung/Nolmung-server, pull requests merged in 2024-12, with the labels that each got.

#55 feat/SV-149: 오늘멍 수정 API 구현
  src/main/java/ureca/nolmung/business/diary/DiaryService.java
  src/main/java/ureca/nolmung/business/diary/DiaryUseCase.java
  src/main/java/ureca/nolmung/business/diary/dto/request/AddDiaryReq.java
  src/main/java/ureca/nolmung/business/diary/dto/request/UpdateDiaryReq.java
  src/main/java/ureca/nolmung/business/diary/dto/response/UpdateDiaryResp.java
  src/main/java/ureca/nolmung/implementation/diary/DiaryExceptionType.java
  src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
  src/main/java/ureca/nolmung/jpa/diary/Diary.java
  src/main/java/ureca/nolmung/persistence/media/MediaRepository.java
  src/main/java/ureca/nolmung/presentation/controller/diary/DiaryController.java
Labels: 💻 기능

#56 feat/SV-154: 사용자 정보 수정 및 조회 API 구현
  src/main/java/ureca/nolmung/business/user/UserService.java
  src/main/java/ureca/nolmung/business/user/UserUseCase.java
  src/main/java/ureca/nolmung/business/user/dto/request/SignUpReq.java
  src/main/java/ureca/nolmung/business/user/dto/request/UserReq.java
  src/main/java/ureca/nolmung/business/user/dto/response/UserResp.java
  src/main/java/ureca/nolmung/implementation/user/UserManager.java
  src/main/java/ureca/nolmung/implementation/user/dtomapper/UserDtoMapper.java
  src/main/java/ureca/nolmung/jpa/user/User.java
  src/main/java/ureca/nolmung/presentation/controller/oauth/MyController.java
  src/main/java/ureca/nolmung/presentation/controller/oauth/UserController.java
Labels: 💻 기능

#57 feat/SV-209: Swagger 관련 어노테이션 추가
  src/main/java/ureca/nolmung/presentation/controller/diary/DiaryController.java
  src/main/java/ureca/nolmung/presentation/controller/review/ReviewController.java
Labels: 💻 기능

#58 refact/SV-144: 사용자 정보 수정 및 조회 api 수정
  src/main/java/ureca/nolmung/business/oauth/OAuth2SucessHandler.java
  src/main/java/ureca/nolmung/business/oauth/OAuthUserServiceImplement.java
  src/main/java/ureca/nolmung/business/oauth/dto/CustomOauth2User.java
  src/main/java/ureca/nolmung/business/user/UserService.java
  src/main/java/ureca/nolmung/business/user/UserUseCase.java
  src/main/java/ureca/nolmung/business/user/dto/response/CustomUserDetails.java
  src/main/java/ureca/nolmung/config/jwt/JWTUtil.java
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ureca/nolmung/config/security/SecurityConfig.java
  src/main/java/ureca/nolmung/implementation/user/UserManager.java
  src/main/java/ureca/nolmung/jpa/user/User.java
  src/main/java/ureca/nolmung/persistence/user/UserRepository.java
  src/main/java/ureca/nolmung/presentation/controller/oauth/UserController.java
Labels: 🛠️ 리팩토링

#59 feat/SV-145: 배지 조회 API 구현
  src/main/java/ureca/nolmung/business/badge/BadgeService.java
  src/main/java/ureca/nolmung/business/badge/BadgeUseCase.java
  src/main/java/ureca/nolmung/business/badge/dto/request/BadgeReq.java
  src/main/java/ureca/nolmung/business/badge/dto/response/BadgeResp.java
  src/main/java/ureca/nolmung/implementation/badge/BadgeManager.java
  src/main/java/ureca/nolmung/implementation/badge/dtomapper/BadgeDtoMapper.java
  src/main/java/ureca/nolmung/persistence/badge/BadgeRepository.java
  src/main/java/ureca/nolmung/presentation/controller/oauth/UserController.java
Labels: 💻 기능

#61 refact/SV-46: @AuthenticationPrincipal을 사용하여 로그인한 사용자 정보 조회 로직 수정
  src/main/java/ureca/nolmung/business/dog/DogService.java
  src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
Labels: 🛠️ 리팩토링

#65 feat/SV-211: 내가 쓴 리뷰 조회 API 구현 및 공통 수정 사항 반영
  src/main/java/ureca/nolmung/business/review/ReviewService.java
  src/main/java/ureca/nolmung/business/review/ReviewUseCase.java
  src/main/java/ureca/nolmung/business/review/dto/response/ReviewLabelResp.java
  src/main/java/ureca/nolmung/business/review/dto/response/ReviewResp.java
  src/main/java/ureca/nolmung/implementation/review/ReviewManager.java
  src/main/java/ureca/nolmung/implementation/review/dtomapper/ReviewDtoMapper.java
  src/main/java/ureca/nolmung/persistence/review/ReviewRepository.java
  src/main/java/ureca/nolmung/presentation/controller/diary/DiaryController.java
  src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
  src/main/java/ureca/nolmung/presentation/controller/dummy/DummyController.java
  src/main/java/ureca/nolmung/presentation/controller/oauth/UserController.java
  src/main/java/ureca/nolmung/presentation/controller/place/PlaceController.java
  src/main/java/ureca/nolmung/presentation/controller/recommend/RecommendController.java
  src/main/java/ureca/nolmung/presentation/controller/review/ReviewController.java
Labels: 💻 기능

#69 feat/SV-212: 오늘멍 작성 시, 배지 추가 로직 구현
  src/main/java/ureca/nolmung/business/diary/DiaryService.java
  src/main/java/ureca/nolmung/implementation/badge/BadgeManager.java
  src/main/java/ureca/nolmung/implementation/badgecode/BadgeCodeException.java
  src/main/java/ureca/nolmung/implementation/badgecode/BadgeCodeExceptionType.java
  src/main/java/ureca/nolmung/jpa/badge/Badge.java
  src/main/java/ureca/nolmung/jpa/user/User.java
  src/main/java/ureca/nolmung/persistence/badge/BadgeRepository.java
  src/main/java/ureca/nolmung/persistence/badgecode/BadgeCodeRepository.java
Labels: 💻 기능

#70 env/SV-88: 개발/운영 서버 환경 분리 작업
  .github/workflows/gradle-dev.yml
  .github/workflows/gradle-prod.yml
  Dockerfile.dev
  Dockerfile.prod
Labels: ⚙️ 환경 설정

#71 feat/SV-144: UserResp에 사용자 프로필, 이메일 정보 추가
  src/main/java/ureca/nolmung/business/user/dto/response/UserResp.java
  src/main/java/ureca/nolmung/implementation/user/dtomapper/UserDtoMapper.java
Labels: 💻 기능

#79 fix/SV-219: 오늘멍 상세조회 응답값 추가
  src/main/java/ureca/nolmung/business/diary/dto/response/DiaryDetailResp.java
  src/main/java/ureca/nolmung/implementation/diary/dtomapper/DiaryDtoMapper.java
Labels: 🔨 수정

#80 refact/sv-218: 추천 시스템 코드 리팩토링
  src/main/java/ureca/nolmung/business/recommend/RecommendService.java
  src/main/java/ureca/nolmung/business/recommend/RecommendUseCase.java
  src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
  src/main/java/ureca/nolmung/implementation/recommend/batch/BatchConfig.java
  src/main/java/ureca/nolmung/implementation/recommend/batch/BatchScheduler.java
  src/main/java/ureca/nolmung/presentation/controller/recommend/RecommendController.java
Labels: 🛠️ 리팩토링

#83 deploy: 24.12.04 추천시스템 추가 수정
  src/main/java/ureca/nolmung/presentation/controller/recommend/RecommendController.java
Labels: 🔨 수정

#84 deploy: 24.12.04 추천 시스템 매니저 수정
  src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
Labels: 🔨 수정

#85 refact/SV-19: 소셜로그인 및 JWT 토큰 인증 로직 기능 리팩토링
  src/main/java/ureca/nolmung/business/oauth/OAuth2SucessHandler.java
  src/main/java/ureca/nolmung/business/oauth/OAuthUserServiceImplement.java
  src/main/java/ureca/nolmung/business/oauth/dto/response/LoginStatus.java
  src/main/java/ureca/nolmung/business/oauth/dto/response/OauthLoginRes.java
  src/main/java/ureca/nolmung/business/user/UserService.java
  src/main/java/ureca/nolmung/business/user/dto/response/UserResp.java
  src/main/java/ureca/nolmung/config/jwt/JWTUtil.java
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ureca/nolmung/config/security/SecurityConfig.java
  src/main/java/ureca/nolmung/exception/Status.java
  src/main/java/ureca/nolmung/implementation/oauth/OauthException.java
  src/main/java/ureca/nolmung/implementation/oauth/OauthExceptionType.java
  src/main/java/ureca/nolmung/implementation/user/dtomapper/UserDtoMapper.java
  src/main/java/ureca/nolmung/presentation/controller/user/OauthController.java
  src/main/java/ureca/nolmung/presentation/controller/user/UserController.java
Labels: 🛠️ 리팩토링

#87 fix/SV-19: 시큐리티 파일 수정
  src/main/java/ureca/nolmung/config/security/SecurityConfig.java
Labels: 🔨 수정

#89 fix/SV-211: GetMapping 수정
  src/main/java/ureca/nolmung/presentation/controller/review/ReviewController.java
Labels: 🐞 버그

#95 Update gradle-prod.yml
  .github/workflows/gradle-prod.yml
Labels: ⚙️ 환경 설정

#98 deploy: 24.12.04 워크플로 수정
  .github/workflows/gradle-dev.yml
  .github/workflows/gradle-prod.yml
  docker-compose-dev.yml
  src/main/java/ureca/nolmung/config/security/SecurityConfig.java
Labels: 🎯 배포

#99 feat/SV-211: 내가 쓴 리뷰 조회 API 에 장소 ID 추가
  src/main/java/ureca/nolmung/business/review/ReviewService.java
  src/main/java/ureca/nolmung/business/review/dto/response/LabelResp.java
  src/main/java/ureca/nolmung/business/review/dto/response/ReviewLabelResp.java
  src/main/java/ureca/nolmung/business/review/dto/response/ReviewResp.java
  src/main/java/ureca/nolmung/implementation/review/dtomapper/ReviewDtoMapper.java
  src/main/java/ureca/nolmung/presentation/controller/review/ReviewController.java
Labels: 🔨 수정

#100 refact/sv-227: 추천 시스템 추가 리팩토링
  src/main/java/ureca/nolmung/business/recommend/RecommendService.java
  src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
  src/main/java/ureca/nolmung/jpa/user/User.java
Labels: 🛠️ 리팩토링, 💻 기능

#101 fix/SV-154 : 사용자 정보 나이에서 생년월일로 수정
  src/main/java/ureca/nolmung/business/user/dto/request/UserReq.java
  src/main/java/ureca/nolmung/business/user/dto/response/UserResp.java
  src/main/java/ureca/nolmung/implementation/user/dtomapper/UserDtoMapper.java
  src/main/java/ureca/nolmung/jpa/user/User.java
Labels: 🔨 수정

#103 feat(SV-222): 장소 조회 필터링 API 수정
  .github/workflows/gradle-dev.yml
  .github/workflows/gradle-prod.yml
  docker-compose.yml
  local-config.yml
  promtail-config.yml
  src/main/java/ureca/nolmung/business/place/PlaceService.java
  src/main/java/ureca/nolmung/business/place/PlaceUseCase.java
  src/main/java/ureca/nolmung/implementation/place/PlaceManager.java
  src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryCustom.java
  src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryImpl.java
  src/main/java/ureca/nolmung/presentation/controller/place/PlaceController.java
Labels: 🛠️ 리팩토링, 💻 기능

#105 refact/SV-226: 다이어리 시스템 리팩토링
  src/main/java/ureca/nolmung/business/diary/DiaryService.java
  src/main/java/ureca/nolmung/persistence/diary/DiaryRepository.java
Labels: 🔨 수정

#106 refact/SV-225 : 소셜 로그인 관련 코드 리팩토링 및 예외처리 추가
  src/main/java/ureca/nolmung/config/jwt/JWTUtil.java
  src/main/java/ureca/nolmung/config/jwt/JwtAccessDeniedHandler.java
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ureca/nolmung/config/security/SecurityConfig.java
  src/main/java/ureca/nolmung/exception/ApiControllerAdvice.java
  src/main/java/ureca/nolmung/exception/jwt/JwtException.java
  src/main/java/ureca/nolmung/exception/jwt/JwtExceptionType.java
  src/main/java/ureca/nolmung/implementation/jwt/JwtTokenException.java
  src/main/java/ureca/nolmung/implementation/jwt/JwtTokenExceptionType.java
Labels: 🛠️ 리팩토링

#107 refact/SV-234: 장소 평균 별점 소수점 첫째자리까지 처리
  src/main/java/ureca/nolmung/jpa/place/Place.java
Labels: 🔨 수정

#108 fix/SV-225 : JWT 토큰 확인 안해도 되는 경로 수정
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
Labels: 🔨 수정, 🐞 버그

#110 refact/SV-33 : DogReq, DogResp 수정
  src/main/java/ureca/nolmung/business/dog/dto/request/DogReq.java
  src/main/java/ureca/nolmung/business/dog/dto/response/DogResp.java
  src/main/java/ureca/nolmung/implementation/dog/DogManager.java
  src/main/java/ureca/nolmung/implementation/dog/dtomapper/DogDtoMapper.java
  src/main/java/ureca/nolmung/jpa/dog/Dog.java
Labels: 🛠️ 리팩토링

#112 deploy: 24.12.06 로깅시스템 구축
  .gitignore
  build.gradle
  src/main/java/ureca/nolmung/business/diary/DiaryService.java
  src/main/java/ureca/nolmung/business/dog/dto/request/DogReq.java
  src/main/java/ureca/nolmung/business/dog/dto/response/DogResp.java
  src/main/java/ureca/nolmung/config/jwt/JWTUtil.java
  src/main/java/ureca/nolmung/config/jwt/JwtAccessDeniedHandler.java
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ureca/nolmung/config/security/SecurityConfig.java
  src/main/java/ureca/nolmung/exception/ApiControllerAdvice.java
  src/main/java/ureca/nolmung/exception/jwt/JwtException.java
  src/main/java/ureca/nolmung/exception/jwt/JwtExceptionType.java
  src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
  src/main/java/ureca/nolmung/implementation/dog/DogManager.java
  src/main/java/ureca/nolmung/implementation/dog/dtomapper/DogDtoMapper.java
  src/main/java/ureca/nolmung/implementation/jwt/JwtTokenException.java
  src/main/java/ureca/nolmung/implementation/jwt/JwtTokenExceptionType.java
  src/main/java/ureca/nolmung/jpa/dog/Dog.java
  src/main/java/ureca/nolmung/jpa/place/Place.java
  src/main/java/ureca/nolmung/persistence/diary/DiaryRepository.java
  src/main/resources/logback-spring.xml
  src/main/resources/logback-variables.properties
Labels: 🎯 배포

#113 refact/sv-233: 거주지 기반 추천 로직 수정
  src/main/java/ureca/nolmung/business/recommend/RecommendService.java
  src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
  src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
Labels: 🛠️ 리팩토링, 💻 기능

#114 refact(SV-90): 로깅 시스템 구축
  build.gradle
  src/main/resources/logback-variables.properties
Labels: ⚙️ 환경 설정

#117 refact(SV-90): 로깅 시스템 구축
  build.gradle
  src/main/resources/logback-spring.xml
  src/main/resources/logback-variables.properties
Labels: ⚙️ 환경 설정

#119 refact(SV-90): 로깅 시스템 구축
  src/main/java/ureca/nolmung/business/place/PlaceService.java
  src/main/resources/logback-spring.xml
Labels: ⚙️ 환경 설정

#123 deploy: 24.12.06 Dockerfile 수정
  Dockerfile.prod
Labels: ⚙️ 환경 설정

#125 fix/SV-61 : JWT 필터 제외할 경로 추가
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
Labels: 🔨 수정

#128 fix/SV-61 : JWT 필터 제외할 경로 수정
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
Labels: 🐞 버그

#135 feat/SV-247: 장소 조회시 북마크 여부 데이터 추가
  .gitignore
  promtail-config.yml
  src/main/java/ureca/nolmung/business/place/PlaceService.java
  src/main/java/ureca/nolmung/business/place/PlaceUseCase.java
  src/main/java/ureca/nolmung/business/place/response/PlaceDetailResponse.java
  src/main/java/ureca/nolmung/business/place/response/SearchedPlaceResponse.java
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ureca/nolmung/config/security/SecurityConfig.java
  src/main/java/ureca/nolmung/implementation/bookmark/BookmarkManager.java
  src/main/java/ureca/nolmung/implementation/place/PlaceManager.java
  src/main/java/ureca/nolmung/implementation/place/dtomapper/PlaceDtoMapper.java
  src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryCustom.java
  src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryImpl.java
  src/main/java/ureca/nolmung/presentation/controller/place/PlaceController.java
  src/main/resources/logback-spring.xml
Labels: 🛠️ 리팩토링

#142 fix/SV-61 : 액세스토큰을 ResponseBody로 받을 수 있도록 수정
  src/main/java/ureca/nolmung/business/oauth/OAuthUserServiceImplement.java
  src/main/java/ureca/nolmung/business/oauth/dto/response/OauthLoginRes.java
  src/main/java/ureca/nolmung/config/jwt/JWTUtil.java
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ureca/nolmung/presentation/controller/user/OauthController.java
Labels: 🔨 수정

#144 fix/SV-261 : 하드코딩된 프론트엔드 URL을 동적 URL로 변경
  src/main/java/ureca/nolmung/presentation/controller/user/OauthController.java
Labels: 🔨 수정

#147 fix/SV-265: 즐겨찾기 목록 조회 시, 장소 id 제공
  src/main/java/ureca/nolmung/business/bookmark/response/BookmarkResponse.java
Labels: 🔨 수정

#148 feat/SV-264 : 404 에러 예외처리 코드 추가
  src/main/java/ureca/nolmung/config/jwt/HttpRequestEndpointChecker.java
  src/main/java/ureca/nolmung/config/jwt/JwtAccessDeniedHandler.java
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ureca/nolmung/config/security/SecurityConfig.java
Labels: 💻 기능

#149 fix/SV-266 : 회원가입 API 결과값에 액세스토큰 포함되도록 수정
  src/main/java/ureca/nolmung/business/user/dto/response/SignUpResp.java
  src/main/java/ureca/nolmung/presentation/controller/user/UserController.java
Labels: 🔨 수정

#137 feat/sv-245: 추천 목록 배치 트리거 구현
  src/main/java/ureca/nolmung/business/bookmark/BookmarkService.java
  src/main/java/ureca/nolmung/business/recommend/RecommendService.java
  src/main/java/ureca/nolmung/business/recommend/RecommendUseCase.java
  src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
  src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
  src/main/java/ureca/nolmung/implementation/recommend/RedisManager.java
  src/main/java/ureca/nolmung/implementation/recommend/batch/BatchConfig.java
  src/main/java/ureca/nolmung/implementation/recommend/batch/BatchScheduler.java
  src/main/java/ureca/nolmung/implementation/user/UserExceptionType.java
  src/main/java/ureca/nolmung/implementation/user/UserManager.java
  src/main/java/ureca/nolmung/jpa/user/User.java
  src/main/java/ureca/nolmung/jpa/userbookmark/UserBookmark.java
  src/main/java/ureca/nolmung/persistence/place/PlaceRepository.java
  src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryImpl.java
  src/main/java/ureca/nolmung/persistence/userbookmark/UserBookmarkRepository.java
Labels: 🛠️ 리팩토링, 🔨 수정, 💻 기능

#152 refact/SV-275: 오늘멍 하루에 하나만 작성가능하도록 예외처리
  src/main/java/ureca/nolmung/business/diary/DiaryService.java
  src/main/java/ureca/nolmung/implementation/diary/DiaryExceptionType.java
  src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
  src/main/java/ureca/nolmung/persistence/diary/DiaryRepository.java
Labels: 🐞 버그

#157 refact/SV-319: 오늘멍 상세조회시 응답값에 작성자 아이디 값 추가
  src/main/java/ureca/nolmung/business/diary/dto/response/DiaryDetailResp.java
  src/main/java/ureca/nolmung/implementation/diary/dtomapper/DiaryDtoMapper.java
Labels: 🔨 수정

#158 refact/sv-320: 추천 리스트 10개로 늘리기
  src/main/java/ureca/nolmung/business/recommend/RecommendService.java
  src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
  src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
  src/main/java/ureca/nolmung/persistence/place/PlaceRepository.java
Labels: 🛠️ 리팩토링, 💻 기능

#159 refact/sv-317: Recommend 엔티티 삭제
  src/main/java/ureca/nolmung/jpa/recommend/Recommend.java
Labels: 🛠️ 리팩토링, 🔨 수정

#162 feat/SV-323 : 오늘 작성한 리뷰 조회 API 구현
  src/main/java/ureca/nolmung/business/review/ReviewService.java
  src/main/java/ureca/nolmung/business/review/ReviewUseCase.java
  src/main/java/ureca/nolmung/business/review/dto/response/ReviewResp.java
  src/main/java/ureca/nolmung/implementation/review/ReviewManager.java
  src/main/java/ureca/nolmung/implementation/review/dtomapper/ReviewDtoMapper.java
  src/main/java/ureca/nolmung/persistence/review/ReviewRepository.java
  src/main/java/ureca/nolmung/presentation/controller/review/ReviewController.java
Labels: 💻 기능

#164 refact/SV-332: 오늘멍 목록 조회시 모든 미디어 반환하도록 수정
  src/main/java/ureca/nolmung/business/diary/dto/response/DiaryListResp.java
  src/main/java/ureca/nolmung/implementation/diary/dtomapper/DiaryDtoMapper.java
  src/main/java/ureca/nolmung/persistence/diary/DiaryRepository.java
Labels: 🐞 버그

#165 fix/SV-334: SecurityConfig CORS 설정 추가
  src/main/java/ureca/nolmung/config/security/SecurityConfig.java
Labels: 🔨 수정

#166 deploy: 24.12.13 v1.0
  src/main/java/ureca/nolmung/business/diary/dto/response/DiaryListResp.java
  src/main/java/ureca/nolmung/config/security/SecurityConfig.java
  src/main/java/ureca/nolmung/implementation/diary/dtomapper/DiaryDtoMapper.java
  src/main/java/ureca/nolmung/persistence/diary/DiaryRepository.java
Labels: 🎯 배포

#167 fix/SV-370: 오늘멍 전체 조회 및 상세 조회시 createdAt값을 LocalDateTime 으로 반환
  src/main/java/ureca/nolmung/business/diary/dto/response/DiaryDetailResp.java
  src/main/java/ureca/nolmung/business/diary/dto/response/DiaryListResp.java
  src/main/java/ureca/nolmung/implementation/diary/dtomapper/DiaryDtoMapper.java
Labels: 🔨 수정

#169 env/SV-373: Dockerfile 타임존 추가
  Dockerfile.dev
  Dockerfile.prod
Labels: ⚙️ 환경 설정

#168 deploy: 24.12.16 v1.0
  Dockerfile.dev
  Dockerfile.prod
  src/main/java/ureca/nolmung/business/diary/dto/response/DiaryDetailResp.java
  src/main/java/ureca/nolmung/business/diary/dto/response/DiaryListResp.java
  src/main/java/ureca/nolmung/implementation/diary/dtomapper/DiaryDtoMapper.java
Labels: 🎯 배포

#171 deploy: 24.12.16 v1.0
  README.md
Labels: 🎯 배포

#172 refact/SV-374: 주석 추가
  src/main/java/ureca/nolmung/business/recommend/RecommendService.java
  src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
  src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
  src/main/java/ureca/nolmung/implementation/recommend/RedisManager.java
  src/main/java/ureca/nolmung/implementation/recommend/batch/BatchConfig.java
Labels: 🛠️ 리팩토링

#184 docs/SV-383: 산출물 링크 수정
  README.md
Labels: 📄 문서

#185 docs/SV-383 : 산출물 링크 수정
  README.md
Labels: 📄 문서

#186 deploy: 24.12.19 v2.0
  README.md
Labels: 🎯 배포

#187 feat/sv-348: personalize 모델 자동 학습 로직 구현
  build.gradle
  src/main/java/ureca/nolmung/config/aws/AwsConfig.java
  src/main/java/ureca/nolmung/implementation/bookmark/BookmarkManager.java
  src/main/java/ureca/nolmung/implementation/recommend/CsvGeneratorManager.java
  src/main/java/ureca/nolmung/implementation/recommend/S3Manager.java
  src/main/java/ureca/nolmung/implementation/recommend/batch/BatchConfig.java
  src/main/java/ureca/nolmung/implementation/recommend/batch/BatchScheduler.java
  src/main/java/ureca/nolmung/persistence/bookmark/BookmarkRepository.java
  src/test/java/ureca/nolmung/implementation/recommend/CsvGeneratorManagerTest.java
Labels: 💻 기능

#188 docs/SV-383: 기획안 링크 수정
  README.md
Labels: 📄 문서

#189 docs/SV-383: 기획안 링크 최종 수정
  README.md
Labels: 📄 문서

#190 deploy: 24.12.19 v2.0
  README.md
  build.gradle
  src/main/java/ureca/nolmung/config/aws/AwsConfig.java
  src/main/java/ureca/nolmung/implementation/bookmark/BookmarkManager.java
  src/main/java/ureca/nolmung/implementation/recommend/CsvGeneratorManager.java
  src/main/java/ureca/nolmung/implementation/recommend/S3Manager.java
  src/main/java/ureca/nolmung/implementation/recommend/batch/BatchConfig.java
  src/main/java/ureca/nolmung/implementation/recommend/batch/BatchScheduler.java
  src/main/java/ureca/nolmung/persistence/bookmark/BookmarkRepository.java
  src/test/java/ureca/nolmung/implementation/recommend/CsvGeneratorManagerTest.java
Labels: 🎯 배포
